name: Build Docker Image and Push to Dockerhub

on:
  push:
    branches:
      - main
      - 'release/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to the Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker image tags using the build number
      - name: Set up Docker image tags
        id: vars
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      # Build the Docker image with tags
      - name: Build Docker image
        run: |
          docker build . \
            -t ${{ secrets.DOCKER_USERNAME }}/selenium_python_chrome:${IMAGE_TAG} \
            -t ${{ secrets.DOCKER_USERNAME }}/selenium_python_chrome:build-${BUILD_NUMBER}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/selenium_python_chrome:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/selenium_python_chrome:build-${BUILD_NUMBER}